# Generated by Django 2.2.9 on 2020-12-24 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=25)),
                ('education', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('houseInfo', models.CharField(max_length=200)),
                ('Maritalstatus', models.CharField(max_length=200)),
                ('Occupation', models.CharField(max_length=200)),
                ('monthySalary', models.CharField(max_length=200)),
                ('OtherMonthlyIncome', models.CharField(max_length=200)),
                ('SavingBalance', models.CharField(max_length=200)),
                ('Investment', models.CharField(max_length=200)),
                ('Property', models.CharField(max_length=200)),
                ('CreditCardLiabilities', models.CharField(max_length=200)),
                ('HomeMortgage', models.CharField(max_length=200)),
                ('OtherLoan', models.CharField(max_length=200)),
                ('Foodspend', models.CharField(max_length=200)),
                ('clothingspend', models.CharField(max_length=200)),
                ('shopping', models.CharField(max_length=200)),
                ('accommodation', models.CharField(max_length=200)),
                ('Transport', models.CharField(max_length=200)),
                ('othersMonthlyspend', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='userLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_text', models.CharField(max_length=10)),
                ('PW_text', models.CharField(max_length=10)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='userinfro',
            name='UserLogin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.userLogin'),
        ),
    ]
